version: '3.8'
services:

  product-search-app:
    image: productsearchapp:0.0.1-SNAPSHOT
    environment:
      - SPRING_ELASTICSEARCH_REST_URIS=elastic-search:9200
    ports:
      - "8080:8080"
    depends_on:
      elastic-search:
        condition: service_healthy

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 3s
      timeout: 30s
      retries: 10